# Generated by Django 5.2.8 on 2025-12-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookProblem',
        ),
        migrations.DeleteModel(
            name='BookSection',
        ),
    ]
