# Generated by Django 5.2.8 on 2025-12-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksection',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
