# Generated by Django 5.2.8 on 2025-12-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_booksection_slug'),
    ]

    operations = [
    ]
