# Generated by Django 5.2.8 on 2025-12-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='solved_count',
            field=models.IntegerField(default=0),
        ),
    ]
