# Generated by Django 5.2.8 on 2025-12-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_solved_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', upload_to='avatars/'),
        ),
    ]
