# Generated by Django 5.2.8 on 2025-12-01 13:12

import apps.submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.submissions.models.user_submission_path),
        ),
    ]
