# Generated by Django 5.2.8 on 2025-12-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_code_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='code_file',
        ),
    ]
