# Generated by Django 5.2.8 on 2025-12-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submission_test_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compilation Error'), ('SE', 'Syntax Error')], default='PENDING', max_length=100),
        ),
    ]
