# Generated by Django 5.2.8 on 2025-12-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_alter_submission_language'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='submission',
            table=None,
        ),
    ]
