# Generated by Django 5.2.8 on 2025-11-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
