# Generated by Django 5.2.8 on 2025-11-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='note',
            field=models.TextField(default='Догадайтесь сами инпуты и аутпуты'),
        ),
    ]
