# Generated by Django 5.2.8 on 2025-11-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
