# Generated by Django 5.2.8 on 2025-11-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_problem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='etalon_solution',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
