# Generated by Django 5.2.8 on 2025-11-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_etalon_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='generator_test',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='etalon_solution',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
