# Generated by Django 5.2.8 on 2025-11-24 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_problem_generator_test_alter_problem_etalon_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
