# Generated by Django 5.2.8 on 2025-11-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_problem_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='checker',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
