# Generated by Django 5.2.8 on 2025-11-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
