# Generated by Django 5.2.8 on 2025-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('javascript', 'JavaScript')], max_length=100),
        ),
    ]
