# Generated by Django 5.2.8 on 2025-11-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_alter_submission_code_alter_submission_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
