# Generated by Django 5.2.8 on 2025-12-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_delete_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input_format',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='note',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_format',
            field=models.TextField(null=True),
        ),
    ]
