# Generated by Django 5.2.8 on 2025-12-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_alter_problem_input_format_alter_problem_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='score',
            field=models.IntegerField(default=20),
        ),
    ]
