# Generated by Django 5.2.8 on 2025-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0016_problem_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
