# Generated by Django 5.2.8 on 2025-12-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0017_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
