# Generated by Django 5.2.8 on 2025-12-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_alter_problem_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='checker',
            field=models.FileField(default=None, null=True, upload_to='problems/<django.db.models.fields.UUIDField>'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='etalon_solution',
            field=models.FileField(default=None, null=True, upload_to='problems/<django.db.models.fields.UUIDField>'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='generator_test',
            field=models.FileField(default=None, null=True, upload_to='problems/<django.db.models.fields.UUIDField>'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
