# Generated by Django 5.2.8 on 2025-12-09 13:31

import apps.problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_alter_problem_checker_alter_problem_etalon_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='checker',
            field=models.FileField(default=None, null=True, upload_to=apps.problems.models.upload_to),
        ),
        migrations.AlterField(
            model_name='problem',
            name='etalon_solution',
            field=models.FileField(default=None, null=True, upload_to=apps.problems.models.upload_to),
        ),
        migrations.AlterField(
            model_name='problem',
            name='generator_test',
            field=models.FileField(default=None, null=True, upload_to=apps.problems.models.upload_to),
        ),
    ]
