# Generated by Django 5.2.8 on 2025-12-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_alter_problem_checker_alter_problem_etalon_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='score',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
