# Generated by Django 5.2.8 on 2025-12-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_alter_problem_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
