# Generated by Django 5.2.8 on 2025-12-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_problem_is_hidden'),
    ]

    operations = [
    ]
