for_tasks = [
    {
        "title": "For1",
        "statement": "Given integers K and N (N > 0), output the number K N times.",
        "input_format": "K N",
        "output_format": "K (N times)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for1/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for1/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for1/checker.py",
        "note": "",
    },
    {
        "title": "For2",
        "statement": "Given two integers A and B (A < B), output in ascending order all integers in the range A to B (including A and B). Also output the amount N of these integers.",
        "input_format": "A B",
        "output_format": "A, ..., B\\nN",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for2/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for2/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for2/checker.py",
        "note": "",
    },
    {
        "title": "For3",
        "statement": "Given two integers A and B (A < B), output in descending order all integers in the range A to B (excluding A and B). Also output the amount N of these integers.",
        "input_format": "A B",
        "output_format": "B-1, ..., A+1\\nN",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for3/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for3/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for3/checker.py",
        "note": "",
    },
    {
        "title": "For4",
        "statement": "Given the price of 1 kg of sweets (as a real number), output the cost of 1, 2, …, 10 kg of these sweets.",
        "input_format": "Price",
        "output_format": "Cost for 1, ..., 10 kg (one per line)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for4/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for4/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for4/checker.py",
        "note": "",
    },
    {
        "title": "For5",
        "statement": "Given the price of 1 kg of sweets (as a real number), output the cost of 0.1, 0.2, …, 1 kg of these sweets.",
        "input_format": "Price",
        "output_format": "Cost for 0.1, ..., 1 kg (one per line)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for5/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for5/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for5/checker.py",
        "note": "",
    },
    {
        "title": "For6",
        "statement": "Given the price of 1 kg of sweets (as a real number), output the cost of 1.2, 1.4, …, 2 kg of these sweets.",
        "input_format": "Price",
        "output_format": "Cost for 1.2, ..., 2 kg (one per line)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for6/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for6/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for6/checker.py",
        "note": "",
    },
    {
        "title": "For7",
        "statement": "Given two integers A and B (A < B), find the sum of all integers in the range A to B inclusive.",
        "input_format": "A B",
        "output_format": "Sum",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for7/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for7/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for7/checker.py",
        "note": "",
    },
    {
        "title": "For8",
        "statement": "Given two integers A and B (A < B), find the product of all integers in the range A to B inclusive.",
        "input_format": "A B",
        "output_format": "Product",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for8/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for8/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for8/checker.py",
        "note": "",
    },
    {
        "title": "For9",
        "statement": "Given two integers A and B (A < B), find the sum of squares of all integers in the range A to B inclusive.",
        "input_format": "A B",
        "output_format": "Sum of squares",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for9/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for9/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for9/checker.py",
        "note": "",
    },
    {
        "title": "For10",
        "statement": "Given an integer N (> 0), find the value of the following sum (as a real number): 1 + 1/2 + 1/3 + … + 1/N.",
        "input_format": "N",
        "output_format": "Sum",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for10/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for10/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for10/checker.py",
        "note": "",
    },
    {
        "title": "For11",
        "statement": "Given an integer N (> 0), find the value of the following sum (as an integer): N^2 + (N + 1)^2 + (N + 2)^2 + … + (2·N)^2.",
        "input_format": "N",
        "output_format": "Sum of squares",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for11/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for11/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for11/checker.py",
        "note": "",
    },
    {
        "title": "For12",
        "statement": "Given an integer N (> 0), find the value of the following product of N factors: 1.1 · 1.2 · 1.3 · …",
        "input_format": "N",
        "output_format": "Product",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for12/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for12/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for12/checker.py",
        "note": "",
    },
    {
        "title": "For13",
        "statement": "Given an integer N (> 0), find the value of the following expression of N terms with alternating signs: 1.1 − 1.2 + 1.3 − … Do not use conditional statements.",
        "input_format": "N",
        "output_format": "Expression value",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for13/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for13/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for13/checker.py",
        "note": "",
    },
    {
        "title": "For14",
        "statement": "Given an integer N (> 0), compute N^2 by means of the formula N^2 = 1 + 3 + 5 + … + (2·N − 1). Output the value of the sum after addition of each term. As a result, squares of all integers in the range 1 to N will be output.",
        "input_format": "N",
        "output_format": "Squares from 1 to N (one per line)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for14/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for14/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for14/checker.py",
        "note": "",
    },
    {
        "title": "For15",
        "statement": "Given a real number A and an integer N (> 0), find A raised to the power N (i.e., the product of N values of A): A^N = A · A · … · A.",
        "input_format": "A N",
        "output_format": "A^N",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for15/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for15/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for15/checker.py",
        "note": "",
    },
    {
        "title": "For16",
        "statement": "A real number A and an integer N (> 0) are given. Using one loop-statement compute and output powers A^K for all integer exponents K in the range 1 to N.",
        "input_format": "A N",
        "output_format": "A^1, ..., A^N (one per line)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for16/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for16/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for16/checker.py",
        "note": "",
    },
    {
        "title": "For17",
        "statement": "A real number A and an integer N (> 0) are given. Using one loop-statement compute the sum 1 + A + A^2 + A^3 + … + A^N.",
        "input_format": "A N",
        "output_format": "Sum",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for17/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for17/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for17/checker.py",
        "note": "",
    },
    {
        "title": "For18",
        "statement": "A real number A and an integer N (> 0) are given. Using one loop-statement compute the expression 1 − A + A^2 − A^3 + … + (−1)^N · A^N. Do not use conditional statements.",
        "input_format": "A N",
        "output_format": "Expression value",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for18/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for18/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for18/checker.py",
        "note": "",
    },
    {
        "title": "For19",
        "statement": "Given an integer N (> 0), find the value of the following product: N! = 1·2·…·N (N-factorial). To avoid the integer overflow, compute the product using a real variable and output the result as a real number.",
        "input_format": "N",
        "output_format": "N! (real number)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for19/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for19/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for19/checker.py",
        "note": "",
    },
    {
        "title": "For20",
        "statement": "An integer N (> 0) is given. Using one loop-statement compute the sum 1! + 2! + 3! + … + N!, where N! (N-factorial) is the product of all integers in the range 1 to N: N! = 1·2·…·N. To avoid the integer overflow, compute the sum using real variables and output the result as a real number.",
        "input_format": "N",
        "output_format": "Sum of factorials (real number)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for20/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for20/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for20/checker.py",
        "note": "",
    },
    {
        "title": "For21",
        "statement": "An integer N (> 0) is given. Using one loop-statement compute the sum 1 + 1/(1!) + 1/(2!) + 1/(3!) + … + 1/(N!), where N! (N-factorial) is the product of all integers in the range 1 to N: N! = 1·2·…·N. The result is an approximate value of the constant e = exp(1).",
        "input_format": "N",
        "output_format": "Approximate value of e",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for21/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for21/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for21/checker.py",
        "note": ""
    },
    {
        "title": "For22",
        "statement": "A real number X and an integer N (> 0) are given. Compute the expression 1 + X + X^2/(2!) + … + X^N/(N!) (N! = 1·2·…·N). The result is an approximate value of exp(X).",
        "input_format": "X N",
        "output_format": "Approximate value of exp(X)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for22/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for22/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for22/checker.py",
        "note": ""
    },
    {
        "title": "For23",
        "statement": "A real number X and an integer N (> 0) are given. Compute the expression X − X^3/(3!) + X^5/(5!) − … + (−1)^N · X^(2·N+1)/((2·N+1)!) (N! = 1·2·…·N). The result is an approximate value of sin(X).",
        "input_format": "X N",
        "output_format": "Approximate value of sin(X)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for23/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for23/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for23/checker.py",
        "note": ""
    },
    {
        "title": "For24",
        "statement": "A real number X and an integer N (> 0) are given. Compute the expression 1 − X^2/(2!) + X^4/(4!) − … + (−1)^N · X^(2·N)/((2·N)!) (N! = 1·2·…·N). The result is an approximate value of cos(X).",
        "input_format": "X N",
        "output_format": "Approximate value of cos(X)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for24/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for24/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for24/checker.py",
        "note": ""
    },
    {
        "title": "For25",
        "statement": "A real number X (|X| < 1) and an integer N (> 0) are given. Compute the expression X − X^2/2 + X^3/3 − … + (−1)^(N−1) · X^N/N. The result is an approximate value of ln(1 + X).",
        "input_format": "X N",
        "output_format": "Approximate value of ln(1 + X)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for25/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for25/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for25/checker.py",
        "note": ""
    },
    {
        "title": "For26",
        "statement": "A real number X (|X| < 1) and an integer N (> 0) are given. Compute the expression X − X^3/3 + X^5/5 − … + (−1)^N · X^(2·N+1)/(2·N+1). The result is an approximate value of atan(X).",
        "input_format": "X N",
        "output_format": "Approximate value of atan(X)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for26/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for26/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for26/checker.py",
        "note": ""
    },
    {
        "title": "For27",
        "statement": "A real number X (|X| < 1) and an integer N (> 0) are given. Compute the expression X + 1·X^3/(2·3) + 1·3·X^5/(2·4·5) + … + 1·3·…·(2·N−1)·X^(2·N+1)/(2·4·…·(2·N)·(2·N+1)). The result is an approximate value of asin(X).",
        "input_format": "X N",
        "output_format": "Approximate value of asin(X)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for27/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for27/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for27/checker.py",
        "note": ""
    },
    {
        "title": "For28",
        "statement": "A real number X (|X| < 1) and an integer N (> 0) are given. Compute the expression 1 + X/2 − 1·X^2/(2·4) + 1·3·X^3/(2·4·6) − … + (−1)^(N−1)·1·3·…·(2·N−3)·X^N/(2·4·…·(2·N)). The result is an approximate value of the square root of 1 + X.",
        "input_format": "X N",
        "output_format": "Approximate value of sqrt(1 + X)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for28/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for28/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for28/checker.py",
        "note": ""
    },
    {
        "title": "For29",
        "statement": "An integer N (> 1) and two points A, B (A < B) on the real axis are given. The segment [A, B] is divided into N sub-segments of equal length. Output the length H of each sub-segment and then output the sequence of points A, A + H, A + 2·H, A + 3·H, …, B, which forms a partition of the segment [A, B].",
        "input_format": "N A B",
        "output_format": "H\\nA, A+H, A+2H, ..., B",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for29/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for29/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for29/checker.py",
        "note": ""
    },
    {
        "title": "For30",
        "statement": "An integer N (> 1) and two points A, B (A < B) on the real axis are given. The segment [A, B] is divided into N sub-segments of equal length. Output the length H of each sub-segment and then output the values of a function F(X) = 1 − sin(X) at points dividing the segment [A, B]: F(A), F(A + H), F(A + 2·H), …, F(B).",
        "input_format": "N A B",
        "output_format": "H\\nF(A), F(A+H), ..., F(B)",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for30/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for30/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for30/checker.py",
        "note": ""
    },
    {
        "title": "For31",
        "statement": "An integer N (> 0) is given. A sequence of real numbers A_K is defined as: A_0 = 2, A_K = 2 + 1/A_(K−1), K = 1, 2, … . Output terms A_1, A_2, …, A_N of the sequence.",
        "input_format": "N",
        "output_format": "A_1, A_2, ..., A_N",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for31/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for31/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for31/checker.py",
        "note": ""
    },
    {
        "title": "For32",
        "statement": "An integer N (> 0) is given. A sequence of real numbers A_K is defined as: A_0 = 1, A_K = (A_(K−1) + 1)/K, K = 1, 2, … . Output terms A_1, A_2, …, A_N of the sequence.",
        "input_format": "N",
        "output_format": "A_1, A_2, ..., A_N",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for32/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for32/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for32/checker.py",
        "note": ""
    },
    {
        "title": "For33",
        "statement": "An integer N (> 0) is given. An integer-valued sequence of the Fibonacci numbers F_K is defined as: F_1 = 1, F_2 = 1, F_K = F_(K−2) + F_(K−1), K = 3, 4, … . Output terms F_1, F_2, …, F_N of the sequence.",
        "input_format": "N",
        "output_format": "F_1, F_2, ..., F_N",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for33/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for33/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for33/checker.py",
        "note": ""
    },
    {
        "title": "For34",
        "statement": "An integer N (> 1) is given. A sequence of real numbers A_K is defined as: A_1 = 1, A_2 = 2, A_K = (A_(K−2) + 2·A_(K−1))/3, K = 3, 4, … . Output terms A_1, A_2, …, A_N of the sequence.",
        "input_format": "N",
        "output_format": "A_1, A_2, ..., A_N",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for34/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for34/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for34/checker.py",
        "note": ""
    },
    {
        "title": "For35",
        "statement": "An integer N (> 2) is given. A sequence of integers A_K is defined as: A_1 = 1, A_2 = 2, A_3 = 3, A_K = A_(K−1) + A_(K−2) − 2·A_(K−3), K = 4, 5, … . Output terms A_1, A_2, …, A_N of the sequence.",
        "input_format": "N",
        "output_format": "A_1, A_2, ..., A_N",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for35/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for35/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for35/checker.py",
        "note": ""
    },
    {
        "title": "For36",
        "statement": "Given positive integers N and K, find the sum 1^K + 2^K + … + N^K. To avoid the integer overflow, compute the sum using real variables and output the result as a real number.",
        "input_format": "N K",
        "output_format": "Sum 1^K + 2^K + ... + N^K",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for36/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for36/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for36/checker.py",
        "note": ""
    },
    {
        "title": "For37",
        "statement": "Given an integer N (> 0), find the sum 1^1 + 2^2 + … + N^N. To avoid the integer overflow, compute the sum using real variables and output the result as a real number.",
        "input_format": "N",
        "output_format": "Sum 1^1 + 2^2 + ... + N^N",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for37/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for37/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for37/checker.py",
        "note": ""
    },
    {
        "title": "For38",
        "statement": "Given an integer N (> 0), find the sum 1^N + 2^(N−1) + … + N^1. To avoid the integer overflow, compute the sum using real variables and output the result as a real number.",
        "input_format": "N",
        "output_format": "Sum 1^N + 2^(N−1) + ... + N^1",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for38/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for38/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for38/checker.py",
        "note": ""
    },
    {
        "title": "For39",
        "statement": "Positive integers A and B (A < B) are given. Output all integers in the range A to B, with an integer of a value K being output K times (for example, the number 3 must be output 3 times).",
        "input_format": "A B",
        "output_format": "Numbers A..B with repetitions by value",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for39/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for39/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for39/checker.py",
        "note": ""
    },
    {
        "title": "For40",
        "statement": "Integers A and B (A < B) are given. Output all integers in the range A to B, with the number A being output once, the number A + 1 being output twice, and so on.",
        "input_format": "A B",
        "output_format": "Numbers A..B with repetitions by order",
        "difficulty": "easy",
        "tag": "for",
        "etalon_solution_path": "/home/anonsina/All/System/Abramyan/for/for40/etalon_solution.py",
        "generator_path": "/home/anonsina/All/System/Abramyan/for/for40/generator.py",
        "checker_path": "/home/anonsina/All/System/Abramyan/for/for40/checker.py",
        "note": ""
    }
]

